### ISSUE TITLE
[App crash]

### ISSUE THREAD

**Issue by charliemenor81** [BobbyESP/Metadator#4]
![Screenshot_2024-07-07-18-23-36-017_com bobbyesp metadator](https://github.com/BobbyESP/Metadator/assets/170799387/f6103128-09b9-4b2c-aa8e-f647f2e69cea)

**Comment by BobbyESP** [comment]
Could you please tell me when that happened? Maybe at the editing page?

**Comment by BobbyESP** [comment]
Due to the lack of information I can't help you. Feel free to reopen the issue in case that you still have the error

**Comment by charliemenor81** [comment]
> Could you please tell me when that happened? Maybe at the editing page?

When download a new music and open the app

**Comment by BobbyESP** [comment]
> > Could you please tell me when that happened? Maybe at the editing page?
> 
> When download a new music and open the app

Okay, thanks. I will publish soon (maybe 1 hour) a new beta version and you tell me if the bug persists

**Comment by BobbyESP** [comment]
@charliemenor81 Try the latest release and tell me if the bug is still there. Thank you!

**Comment by BobbyESP** [comment]
Closing this as no response has been given
